In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])

In [3]:
arr2 = np.array([5,6,7,8], dtype = float)
arr2.dtype


dtype('float64')

In [4]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
np.shape(arr3)

(3, 3)

In [6]:
import numpy as np
import pandas as pd

df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [7]:
import numpy as np
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [8]:
np.array([[8,13,18,4], [25,3,18,28], [14,15,18,24], [1,2,3,4]])

array([[ 8, 13, 18,  4],
       [25,  3, 18, 28],
       [14, 15, 18, 24],
       [ 1,  2,  3,  4]])

In [9]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [10]:
np.random.randint(0, 4, (3, 3))

array([[1, 2, 1],
       [2, 0, 0],
       [3, 1, 2]])

In [11]:
my_array = np.array([x for x in range(10)])

In [12]:
my_array[5]

5

In [13]:
my_array[1:8:3]

array([1, 4, 7])

In [14]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])


In [15]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [16]:
my_array = np.random.randint(1, 100, (4, 6))

In [17]:
my_array

array([[87, 53, 27,  5,  9, 28],
       [19, 54, 40, 26, 56,  3],
       [48, 79, 62,  3,  5, 87],
       [91, 50, 30,  8, 33, 63]])

In [18]:
my_slice = my_array[1:3, 2:4]

In [19]:
my_slice

array([[40, 26],
       [62,  3]])

In [20]:
my_slice[:] = 0

In [21]:
my_array

array([[87, 53, 27,  5,  9, 28],
       [19, 54,  0,  0, 56,  3],
       [48, 79,  0,  0,  5, 87],
       [91, 50, 30,  8, 33, 63]])

In [22]:
a = np.array([3,6,9])
b = np.array([12,15,18])

In [23]:
result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [24]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [26]:
my_array = np.random.randint(0, 10, 20)
my_array.reshape((4,5))

array([[2, 9, 0, 9, 1],
       [1, 3, 0, 5, 6],
       [7, 1, 5, 8, 8],
       [5, 0, 3, 5, 1]])

In [27]:
import pandas as pd
df = pd.DataFrame({
    'year': [2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018],
    'temp': [-4.7, -6.1, -5.5, -3.3, -7.1, -3.1, -5.2, -7.3, -12.1, -6.6, -5.9, -6.3]
})

In [28]:
df.median()

year    2012.5
temp      -6.0
dtype: float64